### ISSUE TITLE
Add "community edition" to version string

### ISSUE THREAD

**Issue by kit494way** [jmespath-community/jp#4]
I think it would be better to clarify that the executable is a community edition.

**Comment by springcomp** [comment]
I fear that adding metadata to the version string would make this package a [prerelease version](https://go.dev/doc/modules/version-numbers) forever ?

**Comment by kit494way** [comment]
It seems I did not express my intention well.
I think it would be better to add "community edition" to the `jp --version` output.
Example:
```sh
$ jp --version
jp version 1.1.0, community edition
```
This can be done by following change.
```diff
--- a/jp.go
+++ b/jp.go
@@ -17,7 +17,7 @@ const version = "1.1.0"
 func main() {
        app := cli.NewApp()
        app.Name = "jp"
-       app.Version = version
+       app.Version = fmt.Sprintf("%s, community edition", version)
        app.Usage = "jp [<options>] <expression>"
        app.Author = ""
        app.Email = ""
```
